export enum IErrors {
	ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED',
	ACCESS_TOKEN_INVALID = 'ACCESS_TOKEN_INVALID',
	REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
	REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
	REFRESH_TOKEN_BLACKLIST = 'REFRESH_TOKEN_BLACKLIST',
	SIGNIN_REQUIRED = 'SIGNIN_REQUIRED',
	NEED_ASK_PERMISSION = 'NEED_ASK_PERMISSION',
	FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',
	NOT_FOUND = 'NOT_FOUND',
	UNAUTHORIZED = 'UNAUTHORIZED',
}

export enum IWsErrors {
	SIGNIN_REQUIRED = 'SIGNIN_REQUIRED',
	FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',
	UNAUTHORIZED = 'UNAUTHORIZED',
}
