export enum enum_email_templates {
    meetingAllVoted = 'meetingAllVoted',
    meetingReminderTomorrow = 'meetingReminderTomorrow',
    scheduleMeetingInviteMultiple = 'scheduleMeetingInviteMultiple',
    meetingUpdated = 'meetingUpdated',
    organizerConfirmedMeeting = 'organizerConfirmedMeeting',
    startMeeting = 'startMeeting',
    meetingReminder30Minutes = 'meetingReminder30Minutes',
    meetingReminderNow = 'meetingReminderNow',
    newVoteReceived = 'newVoteReceived',
    scheduleMeetingsInviteOne = 'scheduleMeetingsInviteOne',
    cancelledMeetingProposal = 'cancelledMeetingProposal',
    cancelledMeeting = 'cancelledMeeting',
    missedMeeting = 'missedMeeting',
    agendaUpdated = 'agendaUpdated',
    agendaAddItem = 'agendaAddItem',
    mentionedAgenda = 'mentionedAgenda',
    sharedMeetingDetailWithYou = 'sharedMeetingDetailWithYou',
    meetingAccessRequested = 'meetingAccessRequested',
    meetingAccessRequestedAccept = 'meetingAccessRequestedAccept',
    meetingAccessRequestedDecline = 'meetingAccessRequestedDecline',
    sharedANoteWithYou = 'sharedANoteWithYou',
    mentionChat = 'mentionChat',
    instantCall = 'instantCall',
    sharedChatWithYou = 'sharedChatWithYou',
    sharedProjectWithYou = 'sharedProjectWithYou',
    bookingMeetingInvite = 'bookingMeetingInvite',
    bookingAcceptDecline = 'bookingAcceptDecline',
    bookingConfirmed = 'bookingConfirmed',
    bookingDeclined = 'bookingDeclined',
    bookingAttendeeCanceled = 'bookingAttendeeCanceled',
    bookingOrganizerCanceled = 'bookingOrganizerCanceled',
    changePassword = 'changePassword',
    changeEmail = 'changeEmail',
    confirmationAccountSignup = 'confirmationAccountSignup',
    confirmationAccountLogin = 'confirmationAccountLogin',
    membersInvitation = 'membersInvitation',
    membersInvitationAccepted = 'membersInvitationAccepted',
    membersInvitationReminder = 'membersInvitationReminder',
    changePasswordSuccessfully = 'changePasswordSuccessfully',
  }
  
  export type IEmailTemplates = keyof typeof enum_email_templates;
  